{% set name = "actflow" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/actflow-{{ version }}.tar.gz
  sha256: 81dad450ca9b75036741a1188321bbcb4edcdedd6226e1163d87bdccf43c6e34

build:
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - gglasso
    - seaborn
    - matplotlib-base
    - numpy <1.24
    - h5py
    - statsmodels
    - wbplot

test:
  imports:
    - ActflowToolbox
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ColeLab/ActflowToolbox
  summary: The Brain Activity Flow (Actflow) Toolbox. Tools to quantify the relationship between connectivity and task activity through network simulations and machine learning prediction. Helps determine how connections contribute to specific brain functions.
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - SammedAdmuthe
